Repository PT07G05-Henry/ecommerce-client, pull requests merged in 2022-10, with the labels that each got.

#5 Estilos, Variables y Fuente de texto global dentro de index.css
  .gitignore
  public/index.html
  src/components/button/button.css
  src/index.css
Labels: enhancement

#6 Feat(client/NavBar): Refactored and Styled NavBar
  src/App.js
  src/components/Home/Home.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/navBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/searchBar.css
  src/containers/Home/Home.jsx
  src/containers/welcome/Welcome.jsx
  src/containers/welcome/welcome.css
Labels: enhancement

#9 Feat(Client/Login): Styled and removed @headlessui/react dependency
  package.json
  pnpm-lock.yaml
  src/components/Account/Account.jsx
  src/components/Account/ButtonLogOut.jsx
  src/components/Account/ButtonLogin.jsx
  src/components/Account/account.css
  src/components/NavBar/NavBar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/searchBar.css
  src/containers/welcome/Welcome.jsx
Labels: enhancement

#13 feat(client/redux): Now redux consume data from the /product and /pro…
  README.md
  src/containers/welcome/Welcome.jsx
  src/store/api.js
Labels: enhancement

#15 feat(client/redux): Updated API consumption
  src/store/api.js
Labels: enhancement

#18 Feat(client/redux): Updated consumption of Users EndPoint
  src/store/api.js
Labels: enhancement

#25 feat(client/redux): updated consumption of /products end point
  src/store/api.js
Labels: enhancement

#27 fix(client/Redux): Fixed broken action creator getProducts
  src/store/api.js
Labels: bug

#28 Feat(Client/React): Styling and new components
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.js
  src/components/Account/Account.jsx
  src/components/Account/account.css
  src/components/Card/Card.jsx
  src/components/Card/card.css
  src/components/Cards/Cards.jsx
  src/components/Cards/cards.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/NavBar/NavBar.jsx
  src/components/loading/Loading.jsx
  src/components/loading/loading.css
  src/components/prueba/prueba.jsx
  src/containers/Home/Home.jsx
  src/containers/Home/home.css
  src/containers/catalog/Catalog.jsx
  src/containers/catalog/catalog.css
  src/containers/webFrame/WebFrame.jsx
  src/index.css
  src/store/api.js
Labels: enhancement

#30 fix(client/NavBar): Fixed broken path
  src/components/Account/Account.jsx
Labels: bug

#32 fix(client/route): Fixed broken route searchByName
  src/App.js
  src/components/SearchBar/SearchBar.jsx
Labels: bug

#34 feat(client/Catalog) added pagination
  package.json
  pnpm-lock.yaml
  src/components/Account/Account.jsx
  src/components/Cards/Cards.jsx
  src/containers/catalog/Catalog.jsx
  src/store/api.js
Labels: enhancement

#36 Feat(client/Redux): Added state for getProductsByName
  src/store/api.js
Labels: enhancement

#39 Feat(Client/Cards): Styling and adding functionality
  src/components/Cards/Cards.jsx
  src/components/Cards/cards.css
Labels: enhancement

#50 feat(Client/Reudux):added cart to the store
  src/store/cart.js
Labels: enhancement

#51 Modularizacion de Redux
  src/store/api.js
  src/store/cart.js
  src/store/categories.js
  src/store/comments.js
  src/store/deliveries.js
  src/store/orders.js
  src/store/payments.js
  src/store/productById.js
  src/store/products.js
  src/store/productsByName.js
  src/store/store.js
  src/store/userById.js
  src/store/users.js
Labels: enhancement

#53 Feat(Client/Cards): Fix return to page 1, replaced old pager without compatibility whit changes on controler, fixed css
  src/components/Cards/Cards.jsx
  src/components/Cards/cards.css
  src/index.css
Labels: enhancement

#58 El nuevo estilo...
  package.json
  pnpm-lock.yaml
  src/assets/Circuit.svg
  src/assets/Logo-Mitad.svg
  src/assets/Logo.svg
  src/components/Account/Account.jsx
  src/components/Account/ButtonLogin.jsx
  src/components/Account/account.css
  src/components/Card/Card.jsx
  src/components/Card/card.css
  src/components/Cards/Cards.jsx
  src/components/Cards/cards.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/navBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/searchBar.css
  src/components/background/Background.jsx
  src/components/background/background.css
  src/components/loading/Loading.jsx
  src/containers/webFrame/WebFrame.jsx
  src/containers/webFrame/webFrame.css
  src/index.css
Labels: enhancement

#60 Feat(Client/style): ProductsDetail styiled an some fixes
  public/favicon.ico
  public/favicon.svg
  public/index.html
  src/assets/Logo1.png
  src/assets/Logo2.png
  src/assets/Logo3.png
  src/assets/Logo4.png
  src/assets/Logo5.png
  src/assets/Logo6.png
  src/assets/Logo7.png
  src/components/ProductDetail/ProductDetail.css
  src/components/ProductDetail/ProductDetail.jsx
  src/containers/webFrame/WebFrame.jsx
Labels: enhancement

#63 Feat(client/Redux): Added getThisUser to redux
  src/components/Account/Account.jsx
  src/components/Account/ButtonLogin.jsx
  src/store/store.js
  src/store/thisUser.js
Labels: enhancement

#77 feat/(API) Admin y Superadmin pueden crear categorias en el dashboard
  src/components/Cards/Cards.jsx
  src/components/CreateCategory/CreateCategory.jsx
  src/components/CreateCategory/createcategory.css
  src/components/DashBoard/DashBoard.jsx
  src/store/api.js
  src/store/categories.js
Labels: Run this with FixCreateCategory in BACKEND
