Repository PT07G05-Henry/ecommerce-client, pull requests merged in 2022-11, with the labels that each got.

#86 Feat(Client/API-Consume): Created api object to give a standar for th…
  api-doc.md
  src/lib/api.js
  src/store/cart.js
  src/store/categories.js
  src/store/comments.js
  src/store/deliveries.js
  src/store/orders.js
  src/store/payments.js
  src/store/productById.js
  src/store/products.js
  src/store/thisUser.js
  src/store/userById.js
  src/store/users.js
Labels: enhancement

#97 Ux update pt1
  src/components/Account/Account.jsx
  src/components/Account/ButtonLogin.jsx
  src/components/Account/account.css
  src/components/Cards/Cards.jsx
  src/components/Cards/cards.css
  src/components/CreateCategory/createcategory.css
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/navBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/searchBar.css
  src/components/SeeProducts/SeeProduct.css
  src/components/SeeProducts/SeeProduct.jsx
  src/containers/Home/Banner.css
  src/containers/Home/Banner.jsx
  src/containers/Home/Home.jsx
  src/containers/SearchByName/SearchByName.jsx
  src/containers/catalog/Catalog.jsx
  src/containers/webFrame/WebFrame.jsx
  src/containers/webFrame/webFrame.css
  src/index.css
  src/lib/api.js
  src/store/store.js
  src/store/window.js
Labels: enhancement

#103 WIP(Client/Style): some components styled - Feat(Clinet/Protection): New component and logic for routing and component protection
  ProtectionAndUserId-doc.md
  api-doc.md
  build/asset-manifest.json
  build/favicon.ico
  build/index.html
  build/logo192.png
  build/logo512.png
  build/manifest.json
  build/robots.txt
  build/static/css/main.ae71d505.css
  build/static/css/main.ae71d505.css.map
  build/static/js/976.162d5eed.chunk.js
  build/static/js/976.162d5eed.chunk.js.map
  build/static/js/main.fa8b9bb5.js
  build/static/js/main.fa8b9bb5.js.LICENSE.txt
  build/static/js/main.fa8b9bb5.js.map
  build/static/media/logo.b2e5a01e505f739f1484b881277d5186.svg
  src/App.js
  src/components/DashBoard/DashBoard.jsx
  src/components/DashBoard/DashBoardOld.css
  src/components/DashBoard/DashBoardOld.jsx
  src/components/DashBoard/dashboard.css
  src/components/Redirect/Redirect.jsx
  src/components/SeeProducts/SeeProduct.css
  src/components/SeeProducts/SeeProduct.jsx
  src/components/protectedFrom/ProtectedFrom.jsx
  src/lib/access.js
  src/store/thisUser.js
Labels: enhancement

#105 Feat(client/style): Dashboard styled
  src/App.js
  src/components/DashBoard/DashBoard.jsx
  src/components/DashBoard/dashboard.css
  src/containers/DashBoard/DashBoard.jsx
  src/containers/DashBoard/DashBoardOld.css
  src/containers/DashBoard/DashBoardOld.jsx
  src/containers/DashBoard/dashboard.css
Labels: enhancement

#106 Feat(client/style)/Fix(Client/Paginated): styled Products component, fixed broken Paginated component
  src/components/Paginated/Paginated.jsx
  src/components/Paginated/PaginatedOld.jsx
  src/components/Paginated/PaginatedOldOld.jsx
  src/components/Products/Products.jsx
  src/components/Products/ProductsOld.jsx
  src/components/Products/products.css
Labels: enhancement

#110 Feat(client/style)/Fix(Client/User): Added functionality to Producst componente, styled Orders, styled and fixed Users, Fixed UX and Style on User Menu
  src/components/Account/Account.jsx
  src/components/Account/account.css
  src/components/Cards/Cards.jsx
  src/components/Orders/Orders.jsx
  src/components/Orders/Paginated.jsx
  src/components/Orders/SortButton.jsx
  src/components/Orders/orders.css
  src/components/Paginated/Paginated.jsx
  src/components/Products/Products.jsx
  src/components/Products/products.css
  src/components/Users/Users.jsx
  src/components/Users/users.css
  src/index.css
  src/store/users.js
Labels: bug, enhancement

#111 User cloud
  src/components/Profile/Profile.jsx
  src/lib/api.js
Labels: help wanted

#114 Feat(Dev/FakeRol): …
  fakeRol.md
  src/components/Account/Account.jsx
  src/components/Account/account.css
  src/store/thisUser.js
Labels: enhancement

#117 Fix(Client/UserImg): fixed broken url
  src/components/Account/Account.jsx
Labels: bug

#118 Fix(Client/UserImg): fixed broken url 2nd time
  src/components/Account/Account.jsx
Labels: bug

#119 Profile update state
  src/components/Profile/Profile.jsx
  src/store/thisUser.js
Labels: enhancement

#125 Feat(Client/Users): Be inmune to a bug from API
  src/components/Users/Users.jsx
Labels: bug

#134 stiled orderDetail
  src/components/OrderDetail/OrderDetail.css
  src/components/OrderDetail/OrderDetail.jsx
Labels: enhancement

#135 stiledCreatedProduct
  src/components/CardCart/cardcart.css
  src/components/CreateProduct/CreateProduct.jsx
  src/components/CreateProduct/createProduct.css
Labels: enhancement

#136 Feat(Client/Cards/Others)
  src/components/Card/Card.jsx
  src/components/Card/card.css
  src/components/Cart/Cart.jsx
  src/components/NavBar/NavBar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/Users/Users.jsx
  src/store/cart.js
  src/store/window.js
Labels: enhancement

#142 stiledCreateCategory
  src/components/CreateCategory/CreateCategory.jsx
  src/components/CreateCategory/createcategory.css
Labels: enhancement

#139 Fix(Client/card): Fixed unabled cart to admin
  src/components/Card/Card.jsx
Labels: bug

#140 Fix(Client/Login): Fixed missing dashboard on login
  src/components/Account/Account.jsx
Labels: bug

#143 feat send Email Order Status Change
  src/components/OrderDetail/OrderDetail.jsx
  src/lib/api.js
Labels: Run this with sendEmail in BACKEND

#144 Fix(Client/cart): fixed infinite loop
  src/App.js
  src/components/Account/Account.jsx
  src/store/cart.js
  src/store/store.js
  src/store/window.js
Labels: bug

#147 Fix(Client/Redux): Fixed changed response on getCart action
  src/store/cart.js
Labels: bug

#148 Feat(Client/Users): added search by name on Users component
  src/components/Users/Users.jsx
Labels: enhancement

#151 stiledProductDetail
  src/components/ProductDetail/Comment.css
  src/components/ProductDetail/Comment.jsx
  src/components/ProductDetail/ProductDetail.css
  src/components/ProductDetail/ProductDetail.jsx
Labels: enhancement

#153 syiledUpdateProduct
  src/components/UpdateProduct/UpdateProduct.css
  src/components/UpdateProduct/UpdateProduct.jsx
Labels: enhancement

#154 Fix(Client/Redux): Fixed cart connection with DB logic
  src/store/cart.js
  src/store/store.js
Labels: bug
